# Change these first
owner: CoopPlayzz # Your GitHub organization or username, where this repository lives
repo: Webstatus-games # The name of this repository

sites:
  - name: Roblox
    url: https://www.roblox.com
    maxResponseTime: 550
  - name: Fortnite
    url: https://fortnite.com
    maxResponseTime: 550
  - name: Minecraft
    url: https://www.minecraft.net
    maxResponseTime: 750

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Webstatus-games
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Website Status
  theme: dark
  introTitle: "**Websites Statuses** is the go to thing to see whats websites down and up"
  introMessage: This website is made with the (very very super big) help of [Upptime bot] (https://upptime.js.org/)
  navbar:
    - title: Electronic Brands
      href: /Webstatus-electronicbrands
    - title: Games
      href: /Webstatus-games
    - title: Sports
      href: /Webstatus-sports
    - title: Other
      href: /Webstatus-other
    - title: Discord
      href: https://discord.gg/MP7eCvk8u6
